// Generated by scripts/process-hero-poster.mjs from the live scene's default
// pose — regenerate both together if the Spline scene changes.
export const HERO_POSTER_SRC = "/assets/hero/robot-poster.webp";
export const HERO_POSTER_BLUR_DATA_URL =
  "data:image/webp;base64,UklGRiYBAABXRUJQVlA4WAoAAAAQAAAACwAADQAAQUxQSKIAAAABgKtt//nl+emPrNG2janN3HgGba6xq901dQhu5Grbtu0+pxERAQp2MxuuKAA60SLp6ICiYrdz5YqqoODhYzuz5uDhjYLD+t2uyO7xvhs03Y3I35+MXbfgc1NuvRS5tRbfB0+OQZtINwwvPjdChkgmVD0dJWJu/PxttiFmd9gH9/OJwfcwfHrtDPJ+ArT7Wgw7RadBShKkBx1Fo1IqkqQNXQFWUDggXgAAANABAJ0BKgwADgADgFolpAAPjk0p8xgAAP7vVFmtJDX/j7Vc7f9aKZj1cGaDFcD3lK/66SGY2L80aeFLrn9jrRS4Kb3+/rw7HayzwndW37T8r7rK94yYWe7bAtsAAAA=";
